### ISSUE TITLE
Adapt it to a JSON parser

### ISSUE THREAD

**Issue by drriguz** [douglascrockford/JSON-c#4]
As you said "It could be adapted to produce a very fast JSON parser."，I'd like to implement a lightweight JSON parser based on it, but then I find it a little difficult.
So is there someone who has already done this job? Or do you have some suggestion to make such a JSON parser?

**Comment by rdpoor** [comment]
FWIW, I'm working on extending JSON_checker's state machine approach to be a full JSON parser.  I'll update this issue if and when I complete it.

**Comment by rdpoor** [comment]
@drriguz As requested, see https://github.com/rdpoor/mu_json

**Comment by drriguz** [comment]
That's awesome!
