### ISSUE TITLE
Include a test suite

### ISSUE THREAD

**Issue by rdpoor** [douglascrockford/JSON-c#6]
At present, it is difficult to know if a change to JSON_checker.c breaks anything or not.  It would be useful to include a validation tests, perhaps by adapting the examples in https://github.com/nst/JSONTestSuite, which contains a trove of test cases, classified as:

- i_<testname>.json -- results may be implementation dependent
- n_<testname>.json -- results should report invalid format
- y_<testname>,json -- results should report valid format

**Comment by douglascrockford** [comment]
Don't let me stop you.

**Comment by rdpoor** [comment]
Standby!  :)

**Comment by rdpoor** [comment]
Cloned repo is ready, shown here so you can preview it:
    https://github.com/rdpoor/JSON-c
In https://github.com/rdpoor/JSON-c/blob/master/test/test_JSON_checker.c, I've commented out all the lines that JSON_checker fails on.  I know there are several so-called "standards" for JSON behavior; I'm not getting involved in that discussion.  But I thought you might be interested in the scanning the cases that did fail.

As soon as I wrap my brain around how to create a proper pull request, I'll do so.

**Comment by rdpoor** [comment]
https://github.com/douglascrockford/JSON-c/pull/8
