### ISSUE TITLE
Elide OB state

### ISSUE THREAD

**Issue by rdpoor** [douglascrockford/JSON-c#7]
At present, after encountering an open curly brace, the parser state is set to ST (expecting string).  It would make more sense to set the state to KE (expecting key).  And once you do that, you can eliminate the OB altogether with two small changes.  As it is now:

```
                 white                                      1-9                                   ABCDF  etc
             space |  {  }  [  ]  :  ,  "  \  /  +  -  .  0  |  a  b  c  d  e  f  l  n  r  s  t  u  |  E  |*/
/*start  GO*/ {GO,GO,-6,__,-5,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__},
/*ok     OK*/ {OK,OK,__,-8,__,-7,__,-3,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__},
/*object OB*/ {OB,OB,__,-9,__,__,__,__,ST,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__},
/*key    KE*/ {KE,KE,__,__,__,__,__,__,ST,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__},

/* { */ case -6:
            if (!push(jc, MODE_KEY)) {
                return reject(jc);
            }
            jc->state = OB;
            break;
```
After eliminating OB state:

```
                 white                                      1-9                                   ABCDF  etc
             space |  {  }  [  ]  :  ,  "  \  /  +  -  .  0  |  a  b  c  d  e  f  l  n  r  s  t  u  |  E  |*/
/*start  GO*/ {GO,GO,-6,__,-5,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__},
/*ok     OK*/ {OK,OK,__,-8,__,-7,__,-3,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__},
/*key    KE*/ {KE,KE,__,-9,__,__,__,__,ST,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__},

/* { */ case -6:
            if (!push(jc, MODE_KEY)) {
                return reject(jc);
            }
            jc->state = KE;  // transition directly to KE (expecting key) state
            break;
```

**Comment by douglascrockford** [comment]
This code is 8 years old. Your suggestion, while commendable, does not fix a defect.

**Comment by rdpoor** [comment]
And it is venerable old code!  I'm making this suggestion since I will be creating a variant for embedded systems where memory space is at a premium.   Of course, that's not a requirement for JSON_checker, so it makes sense to deny this request.

**Comment by douglascrockford** [comment]
I am looking forward to seeing your project.

**Comment by rdpoor** [comment]
> This code is 8 years old. Your suggestion, while commendable, does not fix a defect.

Good call on your part!  After the unit test suite was implemented, it showed that adding my suggested change gave a false positive on trailing commas:
```
    {"id":0,}
```

**Comment by rdpoor** [comment]
> I am looking forward to seeing your project.

Here 'tis: https://github.com/rdpoor/mu_json

Thank you so very much for the state machine approach in JSON-checker.  I extended it to handle producing tokens at the right points.  And (of course) thank you for JSON itself.  You saved the world from XML!  :)
